// MARK: - Init Command

import ArgumentParser
import Foundation
import Logging
import SwiftIndexCore

/// Command to initialize SwiftIndex configuration in a project.
///
/// Usage:
///   swiftindex init
///   swiftindex init --provider mlx
///   swiftindex init --force
struct InitCommand: AsyncParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "init",
        abstract: "Initialize SwiftIndex configuration for a project",
        discussion: """
        Creates a `.swiftindex.toml` configuration file in the current
        directory with sensible defaults for Swift projects.

        The configuration can be customized later by editing the file
        or by passing options to this command.

        Existing configuration files will not be overwritten unless
        --force is specified.
        """
    )

    // MARK: - Options

    @Option(
        name: .shortAndLong,
        help: "Embedding provider to use (mlx, ollama, voyage, openai, swift)"
    )
    var provider: String?

    @Option(
        name: .shortAndLong,
        help: "Embedding model name"
    )
    var model: String?

    @Flag(
        name: .shortAndLong,
        help: "Overwrite existing configuration"
    )
    var force: Bool = false

    @Flag(
        name: .shortAndLong,
        help: "Enable verbose debug output"
    )
    var verbose: Bool = false

    // MARK: - Execution

    mutating func run() async throws {
        let logger = CLIUtils.makeLogger(verbose: verbose)
        logger.info("Initializing SwiftIndex configuration")

        let configPath = ".swiftindex.toml"
        let fullPath = FileManager.default.currentDirectoryPath + "/" + configPath

        // Check if config already exists
        if FileManager.default.fileExists(atPath: fullPath), !force {
            print("Configuration file already exists: \(configPath)")
            print("Use --force to overwrite.")
            throw ExitCode.failure
        }

        // Detect project type and suggest appropriate settings
        let projectInfo = detectProjectInfo()
        logger.debug("Detected project info: \(projectInfo)")

        // Generate configuration content
        let configContent = generateConfigContent(
            provider: provider,
            model: model,
            projectInfo: projectInfo
        )

        // Write configuration file
        do {
            try configContent.write(toFile: fullPath, atomically: true, encoding: .utf8)
            print("Created configuration file: \(configPath)")
            print("")
            printConfigSummary(provider: provider, model: model)
        } catch {
            logger.error("Failed to write configuration: \(error.localizedDescription)")
            throw error
        }

        // Suggest next steps
        print("")
        print("Next steps:")
        print("  1. Review and customize .swiftindex.toml")
        print("  2. Run 'swiftindex index' to build the index")
        print("  3. Run 'swiftindex search <query>' to search your code")

        logger.info("Initialization completed")
    }

    // MARK: - Private Methods

    private func detectProjectInfo() -> ProjectInfo {
        let fm = FileManager.default
        let cwd = fm.currentDirectoryPath

        var info = ProjectInfo()

        // Check for Swift Package Manager
        if fm.fileExists(atPath: cwd + "/Package.swift") {
            info.isSPM = true
        }

        // Check for Xcode project
        let contents = (try? fm.contentsOfDirectory(atPath: cwd)) ?? []
        info.hasXcodeProject = contents.contains { $0.hasSuffix(".xcodeproj") }
        info.hasXcodeWorkspace = contents.contains { $0.hasSuffix(".xcworkspace") }

        // Check for CocoaPods
        if fm.fileExists(atPath: cwd + "/Podfile") {
            info.hasCocoaPods = true
        }

        // Check for Carthage
        if fm.fileExists(atPath: cwd + "/Cartfile") {
            info.hasCarthage = true
        }

        return info
    }

    private func generateConfigContent(
        provider: String?,
        model: String?,
        projectInfo: ProjectInfo
    ) -> String {
        var lines: [String] = []

        // Header comment
        lines.append("# SwiftIndex Configuration")
        lines.append("# Generated by 'swiftindex init'")
        lines.append("")

        // Embedding section
        lines.append("[embedding]")
        if let provider {
            lines.append("provider = \"\(provider)\"")
        } else {
            lines.append("# Provider options: mlx, ollama, voyage, openai, swift")
            lines.append("# Default: auto-detect based on availability")
            lines.append("# provider = \"mlx\"")
        }

        if let model {
            lines.append("model = \"\(model)\"")
        } else {
            lines.append("# model = \"bge-small-en-v1.5\"")
        }

        lines.append("# dimension = 384")
        lines.append("")

        // Search section
        lines.append("[search]")
        lines.append("semantic_weight = 0.7")
        lines.append("rrf_k = 60")
        lines.append("multi_hop_enabled = false")
        lines.append("multi_hop_depth = 2")
        lines.append("")

        // Indexing section
        lines.append("[indexing]")

        // Build exclude patterns based on project type
        var excludePatterns = [".git", ".build", "DerivedData"]

        if projectInfo.hasCocoaPods {
            excludePatterns.append("Pods")
        }

        if projectInfo.hasCarthage {
            excludePatterns.append("Carthage")
        }

        let excludeStr = excludePatterns.map { "\"\($0)\"" }.joined(separator: ", ")
        lines.append("exclude = [\(excludeStr)]")

        lines.append("include_extensions = [\".swift\", \".m\", \".h\"]")
        lines.append("max_file_size = 1000000")
        lines.append("chunk_size = 1500")
        lines.append("chunk_overlap = 200")
        lines.append("")

        // Storage section
        lines.append("[storage]")
        lines.append("index_path = \".swiftindex\"")
        lines.append("# cache_path = \"~/.cache/swiftindex\"")
        lines.append("")

        // API keys section (commented out for security)
        lines.append("[api_keys]")
        lines.append("# Uncomment and fill in if using cloud providers")
        lines.append("# voyage = \"your-voyage-api-key\"")
        lines.append("# openai = \"your-openai-api-key\"")
        lines.append("")

        // Watch section
        lines.append("[watch]")
        lines.append("debounce_ms = 500")
        lines.append("")

        // Logging section
        lines.append("[logging]")
        lines.append("level = \"info\"")

        return lines.joined(separator: "\n")
    }

    private func printConfigSummary(provider: String?, model: String?) {
        print("Configuration summary:")
        print("  Provider: \(provider ?? "auto-detect")")
        print("  Model: \(model ?? "default")")
        print("  Index path: .swiftindex/")
    }
}

// MARK: - ProjectInfo

private struct ProjectInfo {
    var isSPM: Bool = false
    var hasXcodeProject: Bool = false
    var hasXcodeWorkspace: Bool = false
    var hasCocoaPods: Bool = false
    var hasCarthage: Bool = false
}
